server:
  port: 8091
  #tomcat:
  #  max-threads: 10
spring:
  application:
    name: service-order
  zipkin:
    base-url: http://192.168.160.130:9411/ #zipkin server的请求地址
    discovery-client-enabled: false #让nacos把它当成一个url，而不要当做服务名
  sleuth:
    sampler:
      probability: 1.0 #采样百分比
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.160.130:3306/shop?useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.160.130:8848
    sentinel:
      transport:
        port: 9999  #跟控制台交流的端口，随意指定一个未使用的端口即可
        dashboard: 192.168.160.130:8080 #指定控制台服务的地址
      filter:
        enabled: false #关闭sentinel的CommonFilter实例化 实现链路追踪
feign: #开启feign对sentinel的支持
  sentinel:
    enabled: true
  #service-product: #调用的提供者名称
  # ribbon:
  #  NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
