server:
  port: 8091
  #tomcat:
  #  max-threads: 10
spring:
  application:
    name: service-order
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.160.130:3306/shop?useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.160.130:8848
    sentinel:
      transport:
        port: 9999  #跟控制台交流的端口，随意指定一个未使用的端口即可
        dashboard: localhost:8080 #指定控制台服务的地址

  #service-product: #调用的提供者名称
  # ribbon:
  #  NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule