server:
  port: 8081

spring:
  application:
    name: service-product
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.160.130:3306/shop?useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.160.130:8848
